export const SAVE_USER = 'SAVE_USER';
export const POPOLA_POKEMON = 'POPOLA_POKEMON';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const LOGOUT = 'LOGOUT';
export const POPOLA_POKEMON_SELEZIONATO = 'POPOLA_POKEMON_SELEZIONATO';